swagger: "2.0"
info:
  title: nest-api Nest API
  version: "1.0.1"
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://nest-service-rswvzterxa-uc.a.run.app
paths:
  /user/info:
    get:
      security:
        - aad_jwks: []
      operationId: getUserInfo
      responses:
        "200":
          description: OK
securityDefinitions:
  aad_jwks:
    authorizationUrl: https://login.microsoftonline.com/0b3fc178-b730-4e8b-9843-e81259237b77/oauth2/v2.0/authorize
    flow: implicit
    type: oauth2
    x-google-issuer: https://login.microsoftonline.com/0b3fc178-b730-4e8b-9843-e81259237b77/v2.0
    x-google-jwks_uri: https://login.microsoftonline.com/0b3fc178-b730-4e8b-9843-e81259237b77/discovery/v2.0/keys
    x-google-audiences: ddd698ba-1a17-4f0d-a6c1-11c23e367be3
